version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: loja-suplementos
      POSTGRES_USER: loja-suplementos-admin
      POSTGRES_PASSWORD: umasenhanadasegura
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: