version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: suple-store-postgres
    restart: always
    environment:
      POSTGRES_DB: loja-suplementos
      POSTGRES_USER: loja-suplementos-admin
      POSTGRES_PASSWORD: umasenhanadasegura
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: suple-store-app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/loja-suplementos
      SPRING_DATASOURCE_USERNAME: loja-suplementos-admin
      SPRING_DATASOURCE_PASSWORD: umasenhanadasegura
    ports:
      - "8080:8080"

volumes:
  postgres_data:


  docker run --name pgtest -e POSTGRES_PASSWORD=umasenhanadasegura -e POSTGRES_USER=loja-suplementos-admin -e POSTGRES_DB=loja-suplementos -p 5432:5432 -d postgres
